version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/hotel_forest
      - JWT_SECRET=${JWT_SECRET:-секретный_ключ_для_production_замените_на_случайную_строку}
      - JWT_EXPIRES_IN=24h
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-сложный_пароль_для_production}
      - NODE_ENV=production
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://localhost:5000/api
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network
  
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge 